services:
  postgres:
    image: postgres:17
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: financedb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  ml-service:
    build: ./ml
    ports:
      - "5000:5000"
    networks:
      - appnet

  spring-app:
    build: backend         # <- ścieżka do folderu z Dockerfile (dostosuj do siebie)
    container_name: spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/financedb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      ML_SERVICE_URL: http://ml-service:5000/predict/recommendations
    depends_on:
      - postgres
      - ml-service
    networks:
      - appnet
    volumes:
      - ./backend/.env:/app/.env:ro


volumes:
  postgres_data:

networks:
  appnet:
